name: Auto Merge PRs from pranesh-2005

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  pull-requests: write
  contents: write

jobs:
  prmerge:
    runs-on: ubuntu-latest
    if: github.actor == 'pranesh-2005' && github.base_ref == 'main'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Merge PR
        env:
          GH_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          gh pr merge ${{ github.event.pull_request.number }} \
            --merge \
            --delete-branch \
            --admin \
            --repo ${{ github.repository }}
