name: Auto Merge PRs from Pranesh-2005

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review, edited]

permissions:
  contents: write
  pull-requests: write

jobs:
  merge-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Merge PR via GitHub CLI
        if: ${{ github.event.pull_request.user.login == 'Pranesh-2005' }}
        run: |
          gh pr merge ${{ github.event.pull_request.number }} --merge --delete-branch
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
