name: Auto Merge PRs from pranesh-2005

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  automerge:
    runs-on: ubuntu-latest
    if: github.actor == 'pranesh-2005' && github.base_ref == 'main'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up GitHub CLI
        run: |
          sudo apt-get install -y gh

      - name: Authenticate GitHub CLI
        run: echo "${{ secrets.PAT_TOKEN }}" | gh auth login --with-token

      - name: Merge PR
        run: |
          gh pr merge ${{ github.event.pull_request.number }} --merge --delete-branch --admin
